name: marvel_mission_manager
description: "A Flutter project for managing Marvel missions."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  theme_tailor_annotation: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  theme_tailor: ^3.0.2
  build_runner: ^2.4.15

flutter:
  uses-material-design: true
