// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArStdtAZQ50DeKU-lo13dZwh0jam-VrYQ',
    appId: '1:288503693329:web:20506a42ec126e491d71b0',
    messagingSenderId: '288503693329',
    projectId: 'marvel-mission-manager',
    authDomain: 'marvel-mission-manager.firebaseapp.com',
    storageBucket: 'marvel-mission-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD09jd9bNLrNqcJr41FLsOA5XOIXW4Qqeo',
    appId: '1:288503693329:android:7457145e950293e71d71b0',
    messagingSenderId: '288503693329',
    projectId: 'marvel-mission-manager',
    storageBucket: 'marvel-mission-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2-DNMPap5bzNPvMZcLRbwBjvLMmmH46U',
    appId: '1:288503693329:ios:92d6a4dd4db4c42d1d71b0',
    messagingSenderId: '288503693329',
    projectId: 'marvel-mission-manager',
    storageBucket: 'marvel-mission-manager.firebasestorage.app',
    iosBundleId: 'com.example.marvelMissionManager',
  );
}
